import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Text from '../components/AppText/Text'
import Menu from '../components/Menu/Menu'
import LeftBox from '../components/ContentBoxes/LeftBox'
import RightBox from '../components/ContentBoxes/RightBox'
import POTD from '../components/NASA-POTD-API/potd'
import WeatherHome from '../components/WeatherAPI/WeatherHome'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <Text txt="Hi" weight="700" size="70px" color="#0F1C3F"/>
        <Menu />
        <WeatherHome />
        <LeftBox src="/star.png" />
        <RightBox src="/telescope.png"/>
        <POTD />
      </main>
    </div>
  )
}
