import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import Text from '../components/AppText/Text'
import Menu from '../components/Menu/Menu'
import LeftBox from '../components/ContentBoxes/LeftBox'
import RightBox from '../components/ContentBoxes/RightBox'
import POTD from '../components/NASA-POTD-API/potd'
import WeatherHome from '../components/WeatherAPI/WeatherHome'
import Weather from '../components/WeatherAPI/Weather'
import Widget from '../components/Widget'

export default function Home () {
  return(
    <div className={styles.container}>
      <Head>
        <title>Skybound</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/star.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Advent+Pro:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>

        <WeatherHome />
        
        <div>
          <Text txt="Sky Bound" weight="500" size="80px" padding='10px' />
        </div>

        <div className={styles.grid}>
        <Widget icon='/star.png' txt='Star' to='/stars'/>
        <Widget icon='/telescope.png' txt='Space' to='/space'/>
        <Widget icon='/planet.png' txt='Planets' to='/planets'/>
        </div>


        {/* <Menu /> */}
      </main>
    </div>
  )
}