import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Menu from '../components/Menu/Menu'
import HomeButton from '../components/Menu/HomeButton'
import Weather from '../components/WeatherAPI/Weather'
import DateInput from '../components/NASA-POTD-API/DateInput'
import Photo from '../components/NASA-POTD-API/Photo'
import POTD from '../components/NASA-POTD-API/Potd'
import Text from '../components/AppText/Text'
import axios from "axios";

export default function Space() {

  const options = {
    method: 'GET',
    url: 'https://moon-phases-news.p.rapidapi.com/moonnews',
    headers: {
      'X-RapidAPI-Key': 'ea52826d2fmsh17a60f36757e335p191c98jsnca6a688a13e3',
      'X-RapidAPI-Host': 'moon-phases-news.p.rapidapi.com'
    }
  };
  
  axios.request(options).then(function (response) {
    console.log(response.data);
  }).catch(function (error) {
    console.error(error);
  });

  return (
    <div className={styles.spacecontainer}>
      <div className={styles.spacefog}>
      <div className={styles.spacebg}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeButton />
        <Weather />

        <div className={styles.content}>
          <Text txt="The Moon𓇻" font="Astro" weight="500" size="60px"/> <br/><br/>
          <Text txt='Explore our comprehensive guide to understanding the lunar phases including detailed information and images to help track the moons cycle'/> <br/>
        </div>
          
        <Menu />
      </main>
    </div>
    </div>
    </div>
  )
}