import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../components/Menu/Menu'
import HomeButton from '../components/Menu/HomeButton'
import Weather from '../components/WeatherAPI/weather'
import StarCard from '../components/StarCard'
import record from '../database/constellations.json'



export default function Stars() {

  console.log(record);

  return (
    <div className={styles.starscontainer}>
      <div className={styles.starfog}>
      <div className={styles.starsbg}>
      <div className={styles.twinkle}></div>
      <div className={styles.starrybg}></div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeButton />
        <Weather />
        <div className={styles.grid}>
        {
            record.map( (rec, index) => {
              return(
                <div key={index}>
                  <StarCard 
                  src={rec.Image}
                  name={rec.Constellation}
                  genitive={rec.Genitive}
                  meaning={rec.Meaning}
                  star={rec['Brightest star']}
                  />
                  
                </div>
              )
            })
          }
        </div>
        <Menu />
      </main>
    </div>
    </div>
    </div>
  )
}