import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../components/Menu/Menu'
import HomeButton from '../components/Menu/HomeButton'
import Weather from '../components/WeatherAPI/weather'
import StarCard from '../components/StarCard'

export default function Stars() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeButton />
        <Weather />
        <StarCard/>
        {/* <Menu /> */}
      </main>
    </div>
  )
}